//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuadAutomotiveGroupSite.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\r\n        rabbitmq://192.168.79.1/QuadAuto_Web\r\n      ")]
        public string MassTransitRecieveFrom {
            get {
                return ((string)(this["MassTransitRecieveFrom"]));
            }
            set {
                this["MassTransitRecieveFrom"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\r\n        rabbitmq://192.168.79.1/QuadAuto_Web\r\n      ")]
        public string MassTransitRecieveFromDebug {
            get {
                return ((string)(this["MassTransitRecieveFromDebug"]));
            }
            set {
                this["MassTransitRecieveFromDebug"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\r\n        mongodb://192.168.79.1/?safe=true\r\n      ")]
        public string MongoDbConnectionString {
            get {
                return ((string)(this["MongoDbConnectionString"]));
            }
            set {
                this["MongoDbConnectionString"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\r\n        mongodb://192.168.79.1/?safe=true\r\n      ")]
        public string MongoDbConnectionStringDebug {
            get {
                return ((string)(this["MongoDbConnectionStringDebug"]));
            }
            set {
                this["MongoDbConnectionStringDebug"] = value;
            }
        }
    }
}
